# Generated by Django 5.2.8 on 2025-12-06 21:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+254712345678' or '0712345678'", regex='^\\+?254?\\d{9,10}$')])),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_registered'],
            },
        ),
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in liters', max_digits=10)),
                ('collection_date', models.DateField(default=django.utils.timezone.now)),
                ('collection_time', models.TimeField(auto_now_add=True)),
                ('price_per_liter', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('sms_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='broker.farmer')),
            ],
            options={
                'ordering': ['-collection_date', '-collection_time'],
                'unique_together': {('farmer', 'collection_date')},
            },
        ),
    ]
